### ISSUE TITLE
Token error: Missing unauthorized token

### ISSUE THREAD

**Issue by srish** [tonythomas01/gdrive_to_commons#19]
While on my dev setup, I am getting "AuthTokenError at /oauth/complete/mediawiki/", precisely a missing unauthorized token error.  
@tonythomas01 Is it because we are using a different MediaWiki OAuth consumer and I have some old credentials?

**Comment by tonythomas01** [comment]
I think it should be. At this moment, you will have to create a new one with the bulk edit rights which we have and update your `localsettings.py`. Do tell me how this goes. Also see that you are pointing it to `test2.wikipedia.org` for testing.
