### ISSUE TITLE
Improve the design of the main screen that has agreement info

### ISSUE THREAD

**Issue by srish** [tonythomas01/gdrive_to_commons#20]
The current design of the main screen recently added is inconsistent with the other three screens and the information in Step 1-3 boxes are not relevant for the user.

**Comment by srish** [comment]
Made some design changes to the main screen we currently have here: https://tools.wmflabs.org/google-drive-photos-to-commons/; addressed in the commit https://github.com/tonythomas01/gdrive_to_commons/commit/2618c121ddaf6c5d3e504661922ee9a731fd514a.
* For Step 1-3:
  * Removed screenshots and replaced them with icons.
  * Removed descriptions (eg: "Use OAuth login to login to your Wikipedia account!") as they didn't seem relevant for a user.
  * Modified the titles to keep them similar to what we have on the other three screens.
  * Removed the progress bars and replaced them with step icons as they don't seem relevant for homepage.
* Modified the design of the container to align it with the containers on other three (login, picker and upload) screens.
* Replaced the "Drive to Wikipedia Uploader" with the logo format we are using on other screens.
* Modified the statement "I have read the Privacy Policy" to "I've read and accept the Privacy Policy".

![Screen Shot 2019-06-16 at 10 24 03 PM](https://user-images.githubusercontent.com/288353/59583839-55768880-9091-11e9-9d01-b479243e1594.png)

**Comment by tonythomas01** [comment]
Good stuff. Thank you. On first looks, I have 2 issues with the design: 
1. Casing of `Data collection and terms of use`. Lets use heading casing. 
2. Too less spacing above the huge blue `start uploading` button. 

Also, lets see that Google was complaining about consistent branding. I think they are looking for a solid title and a 1-2 liner which is: 
1. Shown here prominently on homepage, 
2. also shown as accurately on the OAuth screen. 

Would've been way easier if we had a logo though :-( We have the logo on the OAuth consent screen and I'm kind of sure that is what they are complaining about.

**Comment by tonythomas01** [comment]
Merged. Now automatically deployed to https://tools.wmflabs.org/google-drive-photos-to-commons/ too!
