### ISSUE TITLE
Arrows not showing up on latest Ubuntu/Firefox (F0DA)

### ISSUE THREAD

**Issue by nicolas-raoul** [tonythomas01/gdrive_to_commons#5]
Ubuntu Linux 2019.04 Firefox 66.0.5 64-bit
![Screenshot from 2019-05-20 13-12-07](https://user-images.githubusercontent.com/99590/57996174-f0b32700-7b00-11e9-951a-61b3289b659c.png)
Thanks!

**Comment by tonythomas01** [comment]
Thank you for reporting. I think the current deployment is missing proper static file handling. Like https://tools.wmflabs.org/google-drive-photos-to-commons/. 

I will look into it (if nobody is in), and fix it this weekend.

**Comment by srish** [comment]
@tonythomas01 I've added the following link https://tools-static.wmflabs.org/cdnjs/ajax/libs/font-awesome/5.8.2/css/all.min.css to replace `css/font-awesome-all.css` in `base.html` in production. This should display the icons properly. 
But, after firing the webservice restart command, I am now getting the `502 bad gateway` error.

**Comment by tonythomas01** [comment]
Thank you. Fixed it, closing it now.
