### ISSUE TITLE
Support editing of media files in Step 3

### ISSUE THREAD

**Issue by srish** [tonythomas01/gdrive_to_commons#6]
After the files have been selected from Google Drive in Step 2, we currently show them for review in Step 3. We display a thumbnail, file name, description, and edit buttons next to each file information. The edit buttons are currently not functional. It would be a nice addition to support editing of file titles and description before uploading them to Wikimedia Commons.

**Comment by tonythomas01** [comment]
I am sorry, but I had to roll this in. Feel free to add more stuff later. I just added editing file name and description with thumbnail. Assigning this to me hence.

**Comment by tonythomas01** [comment]
Done. ✅
